name: Build and Deploy Flask App

on:
  push:
    branches:
      - main # The workflow runs on every push to the `main` branch

jobs:
  # Job 1: Build the Docker image and push it to DockerHub
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 # Retrieve the source code

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app-for-cloud-lab:${{ github.sha }} .    

      - name: Push Docker Image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app-for-cloud-lab:${{ github.sha }}

  # Job 2: Deploy to Azure Container Apps
  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build # This job depends on the `build` job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp create \
            --name flask-app-cloud-lab \
            --resource-group cloud-course-lab \
            --environment flask-app-env \
            --image ${{ secrets.DOCKER_USERNAME }}/flask-app-for-cloud-lab:${{ github.sha }} \
            --target-port 5000 \
            --ingress external \
            --query configuration.ingress.fqdn
